export const shoesAPI = [
  {
    id: 1,
    brand: "Nike",
    model: "Air Max 270",
    description: "Hafif ve nefes alabilir tasarım.",
    price: 150,
    category: "Spor",
    image: "/src/Ayakkabı-API/1.png",
  },

  {
    id: 2,
    brand: "Adidas",
    model: "UltraBoost 22",
    description: "Enerji dönüşümü yüksek koşu ayakkabısı.",
    price: 180,
    category: "Koşu",
    image: "/src/Ayakkabı-API/2.png",
  },
  {
    id: 3,
    brand: "Puma",
    model: "RS-X³",
    description: "Retro ve modernin birleşimi.",
    price: 120,
    category: "Günlük",
    image: "/src/Ayakkabı-API/3.png",
  },
  {
    id: 4,
    brand: "New Balance",
    model: "990v5",
    description: "Üst düzey konfor ve dayanıklılık.",
    price: 175,
    category: "Koşu",
    image: "/src/Ayakkabı-API/4.png",
  },
  {
    id: 5,
    brand: "Reebok",
    model: "Nano X1",
    description: "Fonksiyonel antrenman için ideal.",
    price: 130,
    category: "Fitness",
    image: "/src/Ayakkabı-API/5.png",
  },
  {
    id: 6,
    brand: "Converse",
    model: "Chuck Taylor All Star",
    description: "Klasik ve zamansız sneaker.",
    price: 70,
    category: "Günlük",
    image: "/src/Ayakkabı-API/6.png",
  },
  {
    id: 7,
    brand: "Asics",
    model: "Gel-Kayano 28",
    description: "Yüksek destekli koşu deneyimi.",
    price: 160,
    category: "Koşu",
    image: "/src/Ayakkabı-API/7.png",
  },
  {
    id: 8,
    brand: "Vans",
    model: "Old Skool",
    description: "Kaykay kültürünün simgesi.",
    price: 85,
    category: "Kaykay",
    image: "/src/Ayakkabı-API/8.png",
  },
  {
    id: 9,
    brand: "Under Armour",
    model: "HOVR Phantom 2",
    description: "Yüksek performans koşu ayakkabısı.",
    price: 140,
    category: "Koşu",
    image: "/src/Ayakkabı-API/9.png",
  },
  {
    id: 10,
    brand: "Salomon",
    model: "Speedcross 5",
    description: "Arazi koşuları için üstün tutuş.",
    price: 170,
    category: "Outdoor",
    image: "/src/Ayakkabı-API/10.png",
  },
  {
    id: 11,
    brand: "Jordan",
    model: "Air Jordan 1 Mid",
    description: "Basketbol efsanesi stilinde.",
    price: 190,
    category: "Basketbol",
    image: "/src/Ayakkabı-API/11.png",
  },
  {
    id: 12,
    brand: "Timberland",
    model: "6 Inch Boot",
    description: "Sağlamlık ve stilin birleşimi.",
    price: 200,
    category: "Bot",
    image: "/src/Ayakkabı-API/12.png",
  },
  {
    id: 13,
    brand: "Skechers",
    model: "GOwalk 5",
    description: "Günlük rahatlık için ideal.",
    price: 90,
    category: "Günlük",
    image: "/src/Ayakkabı-API/13.png",
  },
  {
    id: 14,
    brand: "Brooks",
    model: "Ghost 14",
    description: "Yumuşak ve dengeli koşu.",
    price: 140,
    category: "Koşu",
    image: "/src/Ayakkabı-API/14.png",
  },
  {
    id: 15,
    brand: "Mizuno",
    model: "Wave Rider 25",
    description: "Yüksek tepki ve destek.",
    price: 150,
    category: "Koşu",
    image: "/src/Ayakkabı-API/15.png",
  },
  {
    id: 16,
    brand: "Fila",
    model: "Disruptor II",
    description: "Chunky sneaker modasının öncüsü.",
    price: 95,
    category: "Günlük",
    image: "/src/Ayakkabı-API/16.png",
  },
  {
    id: 17,
    brand: "On",
    model: "Cloud X",
    description: "Performans ve rahatlığın buluşması.",
    price: 130,
    category: "Koşu",
    image: "/src/Ayakkabı-API/17.png",
  },
  {
    id: 18,
    brand: "Hoka One One",
    model: "Clifton 8",
    description: "Ultra yumuşak koşu deneyimi.",
    price: 160,
    category: "Koşu",
    image: "/src/Ayakkabı-API/18.png",
  },
  {
    id: 19,
    brand: "Nike",
    model: "ZoomX Vaporfly",
    description: "Yarış için hafif ve hızlı.",
    price: 250,
    category: "Koşu",
    image: "/src/Ayakkabı-API/19.png",
  },

  {
    id: 20,
    brand: "Adidas",
    model: "NMD_R1",
    description: "Şehir stili ve konfor.",
    price: 140,
    category: "Günlük",
    image: "/src/Ayakkabı-API/20.png",
  },
  {
    id: 21,
    brand: "New Balance",
    model: "327",
    description: "Retro tasarım, modern konfor.",
    price: 110,
    category: "Günlük",
    image: "/src/Ayakkabı-API/21.png",
  },
  {
    id: 22,
    brand: "Reebok",
    model: "Club C 85",
    description: "Minimal ve temiz çizgiler.",
    price: 75,
    category: "Günlük",
    image: "/src/Ayakkabı-API/22.png",
  },
  {
    id: 23,
    brand: "Converse",
    model: "One Star",
    description: "Klasik ve şık.",
    price: 80,
    category: "Günlük",
    image: "/src/Ayakkabı-API/23.png",
  },
  {
    id: 24,
    brand: "Asics",
    model: "GT-2000",
    description: "Denge ve destek sağlar.",
    price: 130,
    category: "Koşu",
    image: "/src/Ayakkabı-API/24.png",
  },
  {
    id: 25,
    brand: "Vans",
    model: "Sk8-Hi",
    description: "Yüksek bilekli skate ayakkabısı.",
    price: 90,
    category: "Kaykay",
    image: "/src/Ayakkabı-API/25.png",
  },
  {
    id: 26,
    brand: "Under Armour",
    model: "Project Rock 3",
    description: "Antrenman için güçlendirilmiş.",
    price: 120,
    category: "Fitness",
    image: "/src/Ayakkabı-API/26.png",
  },
  {
    id: 27,
    brand: "Salomon",
    model: "X Ultra 4",
    description: "Zorlu arazi koşulları için.",
    price: 160,
    category: "Outdoor",
    image: "/src/Ayakkabı-API/27.png",
  },
  {
    id: 28,
    brand: "Jordan",
    model: "Why Not Zer0.4",
    description: "Basketbolda agresif stil.",
    price: 140,
    category: "Basketbol",
    image: "/src/Ayakkabı-API/28.png",
  },
  {
    id: 29,
    brand: "Timberland",
    model: "Field Boot",
    description: "Sert hava koşullarına dayanıklı.",
    price: 195,
    category: "Bot",
    image: "/src/Ayakkabı-API/29.png",
  },
  {
    id: 30,
    brand: "Skechers",
    model: "D'Lites",
    description: "Retro görünüm ve rahatlık.",
    price: 85,
    category: "Günlük",
    image: "/src/Ayakkabı-API/30.png",
  },
  {
    id: 31,
    brand: "Brooks",
    model: "Adrenaline GTS 22",
    description: "Destek ve stabilite sağlar.",
    price: 150,
    category: "Koşu",
    image: "/src/Ayakkabı-API/31.png",
  },
  {
    id: 32,
    brand: "Mizuno",
    model: "Inspire 17",
    description: "Koşu sırasında denge için.",
    price: 140,
    category: "Koşu",
    image: "/src/Ayakkabı-API/32.png",
  },
  {
    id: 33,
    brand: "Fila",
    model: "Ray Tracer",
    description: "Modern ve rahat tasarım.",
    price: 95,
    category: "Günlük",
    image: "/src/Ayakkabı-API/33.png",
  },
  {
    id: 34,
    brand: "On",
    model: "Cloudnova",
    description: "Şehir için sportif stil.",
    price: 135,
    category: "Günlük",
    image: "/src/Ayakkabı-API/34.png",
  },
  {
    id: 35,
    brand: "Nike",
    model: "Air Max 280",
    description: "Hafif ve nefes alabilir tasarım.",
    price: 140,
    category: "Spor",
    image: "/src/Ayakkabı-API/35.jpg",
  },
];
